### ISSUE TITLE
有道翻译又修改了规则了

### ISSUE THREAD

**Issue by negunegi** [N0I0C0K/TranslaterCollections#1]
于 2023/2/8测试

**Comment by N0I0C0K** [comment]
我刚刚去测试了一次
V1
![image](https://user-images.githubusercontent.com/30338746/217458283-5b3460ee-970a-4d8e-b180-a9e5e9a7c1ae.png)
V2
![image](https://user-images.githubusercontent.com/30338746/217458390-9e3f0850-e030-46d9-a438-85fec4e5e1b0.png)
V3
![image](https://user-images.githubusercontent.com/30338746/217458344-a135c420-c3c1-4802-8898-1d0460929de1.png)
并没有发现问题

你可以告诉我详细的你发现错误的步骤. 方便我来复现
